from app.schemas.common import (
    ApiResponse,
    BaseSchema,
    CaseContext,
    CaseGovResponse,
    CaseInfo,
    DocumentDraftResult,
    DocumentExtractResult,
    DocumentExtractResultBase,
    DocumentExtractResultDetail,
    DocumentExtractResultSummary,
    DocumentReviewResult,
    DraftDocument,
    DraftDocumentContent,
    LawRetrieval,
    LegalIssueDocumentExtractResult,
    LegalIssue,
    LegalIssueAnalysisResult,
    MainPoint,
    ParsedFields,
    PrecedentInfo,
    PrecedentRetrieval,
    ReviewError,
    StrategyPrecedentAnalysisResult,
)
from app.schemas.document_draft import DocumentDraftRequest, DocumentDraftResponse
from app.schemas.document_extract import DocumentExtractRequest, DocumentExtractResponse
from app.schemas.document_review import DocumentReviewRequest, DocumentReviewResponse
from app.schemas.enums import InputDocumentType, OutputDocumentType, Stage, Status
from app.schemas.legal_issue_analysis import (
    LegalIssueAnalysisRequest,
    LegalIssueAnalysisResponse,
)
from app.schemas.strategy_precedent_analysis import (
    StrategyPrecedentAnalysisRequest,
    StrategyPrecedentAnalysisResponse,
)
from app.schemas.text_embedding import (
    TextEmbeddingRequest,
    TextEmbeddingResponse,
    TextEmbeddingResult,
)

__all__ = [
    "ApiResponse",
    "BaseSchema",
    "CaseContext",
    "CaseGovResponse",
    "CaseInfo",
    "DocumentDraftRequest",
    "DocumentDraftResponse",
    "DocumentDraftResult",
    "DocumentExtractRequest",
    "DocumentExtractResponse",
    "DocumentExtractResult",
    "DocumentExtractResultBase",
    "DocumentExtractResultDetail",
    "DocumentExtractResultSummary",
    "DocumentReviewRequest",
    "DocumentReviewResponse",
    "DocumentReviewResult",
    "DraftDocument",
    "DraftDocumentContent",
    "InputDocumentType",
    "LawRetrieval",
    "LegalIssueDocumentExtractResult",
    "LegalIssue",
    "LegalIssueAnalysisRequest",
    "LegalIssueAnalysisResponse",
    "LegalIssueAnalysisResult",
    "MainPoint",
    "OutputDocumentType",
    "ParsedFields",
    "PrecedentInfo",
    "PrecedentRetrieval",
    "ReviewError",
    "Stage",
    "Status",
    "StrategyPrecedentAnalysisRequest",
    "StrategyPrecedentAnalysisResponse",
    "StrategyPrecedentAnalysisResult",
    "TextEmbeddingRequest",
    "TextEmbeddingResponse",
    "TextEmbeddingResult",
]
