spring:
  application:
    name: objection

  # PostgreSQL
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://3.36.78.186:5432/objection!
    username: ssafy
    password: ssafy

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

jwt:
  secret: objection-secret-key-must-be-at-least-32-bytes-long
  access-expiration: 86400000     # 24시간
  refresh-expiration: 604800000   # 7일

server:
  port: 8080