pipeline {
    agent any

    stages {
        stage('Deploy FastAPI') {
            steps {
                withCredentials([
                    string(credentialsId: 'gms-key', variable: 'GMS_KEY')
                ]) {
                    dir('ai/api/fast_api') {
                        sh '''
                            docker build -t fast-api .

                            docker stop fast-api-container || true
                            docker rm fast-api-container || true

                            docker run -d --name fast-api-container \
                              -p 127.0.0.1:8000:8000 \
                              -e GMS_KEY="$GMS_KEY" \
                              fast-api
                        '''
                    }
                }
            }
        }

        stage('Deploy Data Pipeline') {
            steps {
                sh '''
                    mkdir -p /opt/ai-server/workspace/hadoop-yarn-cluster/data-pipeline
                    rm -rf /opt/ai-server/workspace/hadoop-yarn-cluster/data-pipeline/*
                    cp -r ai/data-pipeline/. /opt/ai-server/workspace/hadoop-yarn-cluster/data-pipeline/

                    cd /opt/ai-server/workspace/hadoop-yarn-cluster
                    docker compose build data-pipeline
                    docker compose up -d data-pipeline
                '''
            }
        }
    }
}